# Generated by Django 5.0.1 on 2024-02-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_meme_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='img',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='name',
        ),
    ]
